- name: DevEnv
  hosts: all
  tasks:
    - name: "Install and configure"
      ansible.builtin.include_tasks: "tasks/{{ task_name }}.yml"
      tags: always
      when: |
        (ansible_run_tags == ['all'] and ansible_skip_tags == [])
        or (task_name in ansible_run_tags)
        or (task_name not in ansible_skip_tags and (task_name in ansible_run_tags or ansible_run_tags == ['all']))
      loop_control:
        loop_var: task_name
      loop:
        - applications
        - beyond_compare
        - code
        - docker
        - git
        - kde
        - konsole
        - krohnkite
        - bismuth
        - zsh
        - rclone_gdrive
