- name: DevEnv
  hosts: all
  roles:
    - role: sicruse.powerline-fonts
      tags: powerline-fonts
    - role: gantsign.oh-my-zsh
      tags: oh-my-zsh
  tasks:
    - name: "Install and configure {{ item }}"
      ansible.builtin.include_tasks: "tasks/{{ item }}.yml"
      loop:
        - applications
        - beyond_compare
        - code
        - docker
        - git
        - kde
        - konsole
        - krohnkite
        - bismuth
        - zsh
        - rclone_gdrive
