- hosts: all

  roles:
    - role: sicruse.powerline-fonts
      vars:
        powerline_fonts:
          - "Meslo\\ Slashed"

  tasks: 
    - include_tasks: tasks/git.yml
    - include_tasks: tasks/beyond_compare.yml
