# Install bismuth (fork of krohnkite)
---
- name: Remove old bismuth Kwin Script
  ansible.builtin.shell:
    cmd: plasmapkg2 -t kwinscript -r bismuth
  register: check_installed
  ignore_errors: true
  tags:
    - bismuth

- name: Install Bismuth package repo
  ansible.builtin.apt_repository:
    repo: deb http://deb.volian.org/volian/ scar main
    state: present
    filename: volian-archive-scar-unstable
  become: true
  tags:
    - bismuth

- name: Install Bismuth repo key
  ansible.builtin.apt_key:
    url: https://deb.volian.org/volian/scar.key
    state: present
    keyring: /etc/apt/trusted.gpg.d/volian-archive-scar-unstable.gpg
  become: true
  tags:
    - bismuth

- name: Update apt repos
  ansible.builtin.apt:
    update_cache: true
  become: true
  tags:
    - bismuth

- name: Install Bismuth
  ansible.builtin.apt:
    name: "kwin-bismuth={{ bismuth_version }}"
    state: present
  become: true
  tags:
    - bismuth
