---
- name: Set double-click to open files and folders
  community.general.ini_file:
    path: "/home/{{ ansible_user_id }}/.config/kdeglobals"
    section: KDE
    option: SingleClick
    value: "false"
    no_extra_spaces: yes
    mode: u=rw,g=r,o=r
  tags:
    - kde

- name: Set shortcuts
  community.general.ini_file:
    path: "/home/{{ ansible_user_id }}/.config/kglobalshortcutsrc"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: yes
    mode: u=rw
  with_items: "{{ global_shortcuts }}"
  tags:
    - kde

- name: Enable Num Lock on startup
  community.general.ini_file:
    path: "/home/{{ ansible_user_id }}/.config/kcminputrc"
    section: "Keyboard"
    option: "NumLock"
    value: "0"
    no_extra_spaces: yes
    mode: u=rw
  tags:
    - kde
