---
- name: Set double-click to open files and folders
  community.general.ini_file:
    path: "/home/{{ ansible_user_id }}/.config/kdeglobals"
    section: KDE
    option: SingleClick
    value: "false"
    no_extra_spaces: yes
    mode: u=rw,g=r,o=r

- name: Set shortcut for Konsole
  community.general.ini_file:
    path: "/home/{{ ansible_user_id }}/.config/kglobalshortcutsrc"
    section: org.kde.konsole.desktop
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: yes
    mode: u=rw
  with_items:
    - option: NewTab
      value: ",none,Open a New Tab"
    - option: NewWindow
      value: "none,none,Open a New Window"
    - option: _k_friendly_name
      value: Launch Konsole
    - option: _launch
      value: Meta+T,none,Launch Konsole

- name: Set shortcut for Dolphin
  community.general.ini_file:
    path: "/home/{{ ansible_user_id }}/.config/kglobalshortcutsrc"
    section: org.kde.dolphin.desktop
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: yes
    mode: u=rw
  with_items:
    - option: _k_friendly_name
      value: Launch Dolphin
    - option: _launch
      value: Meta+E,none,Launch Dolphin
