- name: Install rclone
  ansible.builtin.apt:
    name: rclone
    state: present
  become: true
  tags: rclone

- name: Create user service directory
  ansible.builtin.file:
    path: "~/.config/systemd/user/"
    state: directory
    mode: 0755
  tags: rclone

- name: Install rclone user service
  ansible.builtin.copy:
    src: files/rclone@.service
    dest: "~/.config/systemd/user/rclone@gdrive.service"
    mode: 0644
  tags: rclone

- name: Reload system daemon
  ansible.builtin.systemd:
    daemon-reload: true
  tags: rclone

- name: Ensure rclone service is running
  ansible.builtin.systemd:
    name: rclone@gdrive
    scope: user
    state: started
  tags: rclone
